#!/bin/sh
set -e

case "$1" in
  remove|purge)
    if which update-gconf-defaults >/dev/null 2>&1 && [ -d /usr/share/gconf/mandatory/pantheon ]; then
        update-gconf-defaults --source /usr/share/gconf/pantheon/mandatory \
        --destination /var/lib/gconf/pantheon.mandatory
        update-gconf-defaults --source /usr/share/gconf/pantheon/default \
        --destination /var/lib/gconf/pantheon.default
    fi
    if [ -d /var/lib/gconf/pantheon.mandatory ]; then
        rm -rf /var/lib/gconf/pantheon.mandatory
    fi
    if [ -d /var/lib/gconf/pantheon.default ]; then
        rm -rf /var/lib/gconf/pantheon.default
    fi
    if [ -x /usr/lib/gdm/gdm-set-default-session ] ; then
        /usr/lib/gdm/gdm-set-default-session --remove pantheon || true
    fi
    ;;
esac

#DEBHELPER#
