#!/bin/sh

set -e

if [ "$1" = configure ]; then
  update-alternatives --install /usr/bin/x-session-manager \
    x-session-manager /usr/bin/gnome-session 50 \
    --slave /usr/share/man/man1/x-session-manager.1.gz \
    x-session-manager.1.gz /usr/share/man/man1/gnome-session.1.gz
fi

case "$1" in
  configure|upgrade)
    if [ -x /usr/lib/lightdm/lightdm-set-defaults ] ; then
        /usr/lib/lightdm/lightdm-set-defaults --keep-old --session=pantheon || true
    fi
  ;;
esac

#DEBHELPER#
